resolver: lts-19.5
extra-deps:
- amazonka-1.6.1
- amazonka-core-1.6.1
- amazonka-dynamodb-1.6.1
- amazonka-iam-1.6.1
- amazonka-sts-1.6.1
- aws-easy-0.1.0.0
- http-client-0.6.4.1
- unliftio-core-0.1.2.0
- aeson-1.5.6.0
- base-4.14.3.0
- binary-0.8.9.0
- bytestring-0.11.3.1
- deepseq-1.4.7.0
- text-2.0
- transformers-0.5.6.2
- mtl-2.2.2
- containers-0.6.5.1
- stm-2.5.0.2
- directory-1.3.7.0
- filepath-1.4.2.2
- process-1.6.14.0
- Cabal-3.6.3.0
- time-1.12.1
- array-0.5.4.0
- unix-2.7.2.2
- exceptions-0.10.4
- parsec-3.1.15.0
- pretty-1.1.3.6
- ghc-prim-0.6.1
- ghc-bignum-1.1
